QuizQuizBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: QuizQuizBundle:Default:index }

homepage:
    pattern:  /
    defaults: { _controller: QuizQuizBundle:Default:index }

init_rub:
    pattern:  /init/rubriques
    defaults: { _controller: QuizQuizBundle:Init:importRubriques }
  
init_quiz: 
    pattern:  /init/premier-quiz
    defaults: { _controller: QuizQuizBundle:Init:createQuiz }
    
security_login:
    pattern:  /connexion
    defaults: { _controller: QuizQuizBundle:Security:login }

security_check:
    pattern:  /connexion/verification
    defaults: { _controller: QuizQuizBundle:Security:check }
    
security_logout: 
    pattern:  /deconnexion
    defaults: { _controller: QuizQuizBundle:Security:logout }