imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } 
    session:
        default_locale: %locale%
        auto_start:     true

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        closure:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.6.jar
        yui_js:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.6.jar
        yui_css:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.6.jar

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        
        mappings:
            StofDoctrineExtensionsBundle: ~
            QuizQuizBundle: ~

swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

stof_doctrine_extensions:
    default_locale: fr_BE
    orm: 
        default: 
            tree: true
            timestampable: true
            sluggable: true
            loggable: true
            translatable: false
            
sensio_framework_extra: ~

fos_user: 
    db_driver:       orm
    firewall_name:   main
    user_class:      Quiz\QuizBundle\Entity\User
    group:
        group_class: Quiz\QuizBundle\Entity\Group
        
winzou_cache:
    options: 
        cache_dir: %kernel.cache_dir%/cache
#        default_driver: lifetimefile