security:
#    acl:
#        connection: default
        
#    encoders:
#        Symfony\Component\Security\Core\User\User: sha1

    role_hierarchy:
        # ROLE_USER
        ROLE_RESP:  ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_RESP]

    providers:
        fos_userbundle:
            id: fos_user.user_manager
#        main: 
#            entity: { class: Quiz\QuizBundle\Entity\User, property: username }
#            id: dvp.user_provider
      
#        in_memory:
#            users:
#                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/
            form_login:
#                provider:   fos_userbundle
                login_path: /connexion
                check_path: /connexion/verification
            logout:
                path:       /deconnexion
                target:     /
            anonymous:      true
            
        sf2gen:
            pattern:    /_sf2gencdt/.*
            security:  false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        
        # tout le monde peut créer des quiz (mais pas partout : il faut qu'un resp autorise 
        # la personne à créer des quiz rubriques pour qu'ils apparaissent dans les listes, 
        # sinon accès si on a un lien exclusivement - validable par resp au besoin). 
        - { path: ^/creer, roles: ROLE_USER }
        # il faut être resp pour avoir accès au panel d'admin
        - { path: ^/admin, roles: ROLE_RESP } 
        # pour les opérations rares et lourdes, il faut être superadmin
        - { path: ^/superadmin, roles: ROLE_ADMIN } 