security:
#    acl:
#        connection: default

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/
            form_login:
                login_path: /connexion
                check_path: /connexion/verification
            logout:
                path:       /deconnexion
                target:     /
            anonymous:      true
            remember_me: 
                key:        "AA„EE„II„MM„QQ„UU„Y"
            
        sf2gen:
            pattern:    /_sf2gencdt/.*
            security:  false

    access_control:
        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }