security:
    acl:
        connection: default
        
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        # ROLE_USER
        ROLE_RESP:  ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_RESP]

    providers:
        main: 
            entity: { class: Quiz\QuizBundle\Entity\User, property: username }
#            id: user_provider.quiz
      
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login: 
                login_path: /connexion
                check_path: /connexion/verification
            
        sf2gen:
            pattern:    /_sf2gencdt/.*
            security:  false

    access_control:
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        
        # tout le monde peut créer des quiz (mais pas partout : il faut qu'un resp autorise 
        # la personne à créer des quiz rubriques pour qu'ils apparaissent dans les listes, 
        # sinon accès si on a un lien exclusivement - validable par resp au besoin). 
        - { path: ^/creer, roles: ROLE_USER }
        # il faut être resp pour avoir accès au panel d'admin
        - { path: ^/admin, roles: ROLE_RESP } 
        # pour les opérations rares et lourdes, il faut être superadmin
        - { path: ^/superadmin, roles: ROLE_ADMIN } 
        
#    factories: 
#        - "%kernel.root_dir%/../src/Quiz/QuizBundle/Resources/config/security_factories.xml"